openapi: 3.0.0
info:
  title: SHIBAINU API
  version: 0.0.1
servers:
  - url: http://localhost:3000/api
paths:
  /api/v1/pages/:
    get:
      summary: Returns a list of pages
      description: Optional extended description in CommonMark or HTML.
      responses:
        '200':    # status code
          description: A JSON array
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string